# -*- coding: utf-8 -*-
"""Triade_APP_Prototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1cvTNY97WHNkQaoV8ySgfA2x9vGsHxK
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# 
# # --- CONFIG PAGE ---
# st.set_page_config(page_title="LA TRIADE", page_icon="🎬", layout="wide")
# 
# # CSS pour nettoyer les liens (enlever le soulignement moche)
# st.markdown("""
# <style>
#     a {text-decoration: none; color: inherit; font-weight: bold;}
#     a:hover {color: #ff4b4b; text-decoration: underline;}
#     .metric-card {background-color: #f0f2f6; border-radius: 10px; padding: 20px;}
# </style>
# """, unsafe_allow_html=True)
# 
# # --- CHARGEMENT ---
# @st.cache_data
# def load_and_prep():
#     # ATTENTION : Assure-toi d'avoir uploadé la V2 ici
#     try:
#         df = pd.read_csv('Triade_TAGGED_SOUP_V2.csv')
#     except:
#         df = pd.read_csv('Triade_TAGGED_SOUP.csv') # Fallback ancien fichier
# 
#     df['soup'] = df['soup'].fillna('')
# 
#     # Création Matrice
#     count = CountVectorizer(stop_words='english')
#     count_matrix = count.fit_transform(df['soup'])
#     cosine_sim = cosine_similarity(count_matrix, count_matrix)
# 
#     indices = pd.Series(df.index, index=df['name'].str.lower()).drop_duplicates()
#     return df, cosine_sim, indices
# 
# try:
#     df, cosine_sim, indices = load_and_prep()
# except Exception as e:
#     st.error("Il manque le fichier CSV ! Uploade-le dans le menu de gauche.")
#     st.stop()
# 
# # --- MOTEUR ---
# def get_recommendations(title):
#     title = title.lower()
#     if title not in indices: return None
# 
#     idx = indices[title]
#     if isinstance(idx, pd.Series): idx = idx.iloc[0]
# 
#     sim_scores = list(enumerate(cosine_sim[idx]))
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
#     sim_scores = sim_scores[1:60] # On cherche un peu plus large (top 60)
#     movie_indices = [i[0] for i in sim_scores]
# 
#     return df.iloc[movie_indices]
# 
# # --- FONCTION D'AFFICHAGE D'UNE CARTE ---
# def display_card(category_name, description, df_results, category_filter, emoji, metric_col, metric_label):
#     st.markdown(f"### {emoji} {category_name}")
#     st.caption(description)
# 
#     # Filtrage
#     rec = df_results[df_results['Category'] == category_filter].head(1)
# 
#     if not rec.empty:
#         film = rec.iloc[0]
# 
#         # Titre avec Lien Letterboxd
#         url = film['film_url'] if 'film_url' in film else "#"
#         st.markdown(f"#### [{film['name']}]({url})")
# 
#         # Infos : Année | Note
#         rating = f"⭐ {film['rating']}" if 'rating' in film else ""
#         st.write(f"{int(film['year'])} • {rating}")
# 
#         # La Métrique Spécifique (Vues ou Ratio)
#         if metric_col == 'watches':
#             st.metric(metric_label, f"{int(film['watches']):,}")
#         elif metric_col == 'like_ratio':
#             # Sécurité calcul
#             try:
#                 ratio = film['likes'] / film['watches'] if film['watches'] > 0 else 0
#                 st.metric(metric_label, f"{ratio:.1%}")
#             except:
#                 st.metric(metric_label, "N/A")
# 
#         # Petit bouton discret
#         st.markdown(f"[Voir sur Letterboxd ↗]({url})")
# 
#     else:
#         st.warning(f"Pas de {category_name} similaire trouvé.")
# 
# # --- INTERFACE ---
# st.title("🎬 LA TRIADE v2")
# st.write("Keywords & Genres prioritaires • Liens Letterboxd intégrés")
# 
# selected_movie = st.selectbox("Tu as aimé quel film ?", df['name'].sort_values().unique())
# 
# if st.button('Lancer la recherche'):
#     results = get_recommendations(selected_movie)
# 
#     if results is not None:
#         st.write("---")
#         st.subheader(f"Parce que tu as aimé *{selected_movie}* :")
# 
#         col1, col2, col3 = st.columns(3)
# 
#         with col1:
#             display_card("LA VALEUR SÛRE", "(Blockbuster)", results, 'Blockbuster', "🏛️", 'watches', "Vues")
# 
#         with col2:
#             display_card("LE CHOIX CULTE", "(Cinéphiles)", results, 'Culte', "🎸", 'watches', "Vues")
# 
#         with col3:
#             display_card("LA PÉPITE", "(Hidden Gem)", results, 'Pépite', "💎", 'like_ratio', "Like Ratio")
# 
#     else:
#         st.error("Film introuvable.")